spring.application.name=user-profile-service
server.port=${PORT:8084}

pluto.authservice.url=${AUTH_SERVICE_URL:http://localhost:8081}
pluto.problemservice.url=${PROBLEM_SERVICE_URL:http://localhost:8082}
pluto.submissionservice.url=${SUBMISSION_SERVICE_URL:http://localhost:8083}
